---
- hosts: localhost
  tasks:
    - name: Install pwgen
      package: name=pwgen state=latest
    - name: Generate password
      shell: pwgen -N 1 -s 30
      register: mypass
    - name: Print the generated password, display all register variables
      debug:
        msg: "The password is {{ mypass }}" 
    - name: Print only the generated password
      debug:
        msg: "The password is {{ mypass.stdout }}" 